### ISSUE TITLE
Wrong npm install command

### ISSUE THREAD

**Issue by federicopenaranda** [Hyperxq/Project-Builder-schematics-docs#31]
In this page: https://schematics.pbuilder.dev/getting-started/first-steps/ the npm command to install the tool is `npm i -g @builder/cli` and it doesn't find the package, it should be `npm i -g @pbuilder/cli`

**Comment by Hyperxq** [comment]
thank you so much @federicopenaranda ! the bug is already solved!

**Comment by federicopenaranda** [comment]
No problem, thank you!, I have been looking for this for many years now!, awesome content.
