### ISSUE TITLE
Error when creating a schematic

### ISSUE THREAD

**Issue by federicopenaranda** [Hyperxq/Project-Builder-schematics-docs#43]
Hi, I'm trying to create a new schematic with the example command, but I'm getting this, am I doing something wrong?, Thanks!

![image](https://github.com/Hyperxq/Project-Builder-schematics-docs/assets/7416569/0f40f348-0d49-400e-b9ec-2be36cf38326)

**Comment by Hyperxq** [comment]
Hi @federicopenaranda,

Which CLI version do you have?

To know it, execute:
```sh
builder --version
```

**Comment by Hyperxq** [comment]
The last one is the 1.6.7. If you have a lower one, try to upgrade to the last one.

**Comment by federicopenaranda** [comment]
The pproblem was that I didn't create the project before the schematic, my bad.
