### ISSUE TITLE
npm link typo?

### ISSUE THREAD

**Issue by federicopenaranda** [Hyperxq/Project-Builder-schematics-docs#44]
I think that in this part, the command to test the schematic should be:

`npm run build && cd dist && npm link`

instead of:

`npm run build && cd dist && npm link ./dist`  I got a wrong path error with this

Also, how do I run that schematic in another folder?, npm link enabled to use it globally, but I couldn't make it work, it couldn't find the command. Maybe adding that to the tutorial?.

**Comment by Hyperxq** [comment]
You have 3 ways:
1. use the `dist` folder:  https://schematics.pbuilder.dev/tutorials/my-first-schematic/#create-the-first-schematic
```sh
builder exec [relative-dist-schematic-project-path] [schematic-name]
```
2. Use [verdaccio](https://schematics.pbuilder.dev/tutorials/test-your-schematic/#verdaccio):
To use verdaccio you need to configure an npm user.

3. Use npm link.

**Comment by Hyperxq** [comment]
Using `npm link` is very similar to verdaccio. 
I recommend to use the first one to test it but if you want to test the behavior of your schematic try with verdaccio.

**Comment by federicopenaranda** [comment]
I will, thank you!.

**Comment by Hyperxq** [comment]
@federicopenaranda if you still having problem with it. Please tell me and I will see how can I help you

**Comment by federicopenaranda** [comment]
Thank you very much!, yes, I will read more and try what you suggested before I ask for your help. Cheers!

**Comment by federicopenaranda** [comment]
No luck Daniel, I tried this command in the project builder folder "builder exec ./dist/collection.json angular-add-tailwind-imports" and it works, but when I try to execute it from a different folder I get this error:

![image](https://github.com/Hyperxq/Project-Builder-schematics-docs/assets/7416569/8eb4a163-6191-474d-998e-db37483c2794)

I tried absolute and relative path, it looks like is looking for the package.json file and tries to create a temp project because it doesn't find it.

**Comment by Hyperxq** [comment]
@federicopenaranda sorry for my delayed answer! I've been having too much work.

When you are using the pbuilder cli to test local schematics you need to see the next things:

- You need to understand where is your schematic project and where is your target project in your computer.
- When you compile your schematic project you need to reference the `collection.json` that you have in the folder `dist`.
- When you will run your schematic you need to know where is your schematic project.

Root
|___ demos
        |___ your-schematic-project
|___ projects
        |___ your-target-project
        
If you want to execute your schematic in your target project you need to two things:

1. Compile your schematic project.
2. reference your schematic project from your target project: ../demos/your-schematic-project

**Comment by federicopenaranda** [comment]
Hi Daniel, playing around following you advise, I finally made it work!, the trick was to reference the dist folder alone, not with the "collection.json" file, that way the command found the package.json file and made it to install all the packages, it was trying to look into dist\collection.json\package.json path, this is the error that gave me the tip: `npm error path D:\AppFactory\appfactory\schematics\dist\collection.json\package.json.` Thanks for the help!.

I think it can be helpful to create a video or tutorial that shows the whole process, from an empty folder to applying more than one schematic to a real Angular app, that would be soooo helpful to fully understand schematics. I can volunteer to help you if you need a hand.

**Comment by Hyperxq** [comment]
For sure! 

I created a slack channel, please write there to talk more about it!

https://schematicsforhumans.slack.com/archives/C07C2HYTUCS
